<?php
require __DIR__.'/../.besttop10-private/app/bootstrap.php';
require ROOT.'/app/layout.php';
$page=(string)($_GET['page']??'home');
$requestPath=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH);
if(!in_array($requestPath,['/','/index.php'],true)){http_response_code(404);$page='404';}
$join='SELECT r.*,c.name AS category,c.slug AS category_slug FROM reviews r JOIN categories c ON c.id=r.category_id ';
$cats=categories();
if ($page==='review') {
 $review=query($join.'WHERE r.slug=? AND r.status="published"',[(string)($_GET['slug']??'')])[0]??null;
 if(!$review) { http_response_code(404); $page='404'; }
}
$valid=['home','review','reviews','top10','categories','about','privacy','compare','404'];
if(!in_array($page,$valid,true)){http_response_code(404);$page='404';}
headerView($page==='home'?'':($page==='review'?$review['title']:ucfirst($page)),$page==='review'?$review['excerpt']:'');
?>
<main id="main">
<?php if($page==='home'):
 $latest=query($join.'WHERE r.status="published" ORDER BY r.featured DESC,r.updated_at DESC,r.id ASC LIMIT 3');
 $featured=query($join.'WHERE r.status="published" AND r.score>0 ORDER BY r.featured DESC,r.score DESC LIMIT 1')[0]??null;
?>
<section class="relative overflow-hidden"><div class="wrap grid items-center gap-8 py-12 md:min-h-[475px] md:grid-cols-2 md:py-16"><div class="relative z-10"><div class="eyebrow mb-6 flex items-center gap-2"><span class="h-1.5 w-1.5 rounded-full bg-teal"></span>Less guesswork. Better choices.</div><h1 class="max-w-xl text-[43px] leading-[1.06] tracking-[-0.045em] sm:text-6xl lg:text-[66px]"><?= e(setting('tagline')) ?></h1><p class="mt-6 max-w-md text-base leading-7 text-muted"><?= e(setting('description')) ?></p><form action="/" class="mt-7 flex max-w-lg gap-2 rounded-lg border border-ink/15 bg-white p-2 shadow-sm"><input type="hidden" name="page" value="reviews"><label for="hero-search" class="sr-only">Search reviews</label><span class="hidden items-center pl-3 text-muted sm:flex"><?= icon('search') ?></span><input id="hero-search" name="q" class="w-full flex-1 px-2 text-sm outline-none" placeholder="What are you looking for?"><button class="btn" type="submit">Search</button></form><div class="mt-5 flex flex-wrap gap-2 text-xs text-muted"><span>Popular:</span><a class="underline decoration-ink/20 underline-offset-4" href="/?page=reviews&q=headphones">Headphones</a><span>·</span><a class="underline decoration-ink/20 underline-offset-4" href="/?page=reviews&category=travel">Travel essentials</a><span>·</span><a class="underline decoration-ink/20 underline-offset-4" href="/?page=reviews&category=home-improvement">Home upgrades</a></div></div><div class="relative"><img src="/assets/hero.jpg" alt="Headphones on a warm neutral background" class="h-[310px] w-full rounded-2xl object-cover sm:h-[390px]" fetchpriority="high"><div class="absolute -bottom-4 left-4 rounded-lg border border-ink/5 bg-white p-4 shadow-lg sm:left-7"><p class="eyebrow">The review edit</p><p class="mt-1 font-serif text-xl">Find your next favourite.</p><a href="/?page=reviews" class="mt-2 inline-flex items-center gap-2 text-xs font-semibold text-teal">Explore reviews <?= icon('arrow','h-4 w-4') ?></a></div><span class="absolute right-4 top-4 rounded-full bg-white/95 px-3 py-2 text-[10px] font-semibold uppercase tracking-widest">Thoughtfully compared</span></div></div></section>
<section class="mt-5 border-y border-ink/10 bg-white/50"><div class="wrap grid grid-cols-2 divide-ink/10 sm:grid-cols-3 lg:grid-cols-6"><?php foreach(array_slice($cats,0,6) as $c): ?><a href="/?page=reviews&category=<?= e($c['slug']) ?>" class="flex items-center justify-center gap-3 border-ink/10 px-2 py-6 text-xs font-semibold transition hover:bg-teal/5 sm:text-sm"><?= icon($c['icon']) ?><span><?= e($c['name']) ?></span></a><?php endforeach ?></div></section>
<section class="wrap py-14"><div class="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow mb-3">The latest word</p><h2 class="text-3xl tracking-tight sm:text-4xl">Reviews worth your time</h2></div><a href="/?page=reviews" class="inline-flex items-center gap-2 text-sm font-semibold text-teal">See all reviews <?= icon('arrow','h-4 w-4') ?></a></div><div class="grid gap-9 md:grid-cols-3"><?php foreach($latest as $r) reviewCard($r); ?></div></section>
<?php if($featured): ?><section class="border-y border-ink/10 bg-[#eeede7]"><div class="wrap grid gap-8 py-10 md:grid-cols-12 md:items-center"><div class="md:col-span-3"><p class="eyebrow mb-4">Beyond the star rating</p><h2 class="text-4xl leading-tight tracking-tight">A closer look<br>before you buy.</h2><p class="mt-4 text-sm leading-6 text-muted">The useful details. The honest trade-offs. A clearer picture of what works for you.</p></div><img src="<?= e($featured['image']) ?>" class="h-72 w-full rounded-lg object-cover md:col-span-4" alt="<?= e($featured['title']) ?>" loading="lazy"><div class="md:col-span-5"><div class="flex items-center justify-between gap-4"><p class="eyebrow">Featured <?= $featured['demo']?'sample ':'' ?>review</p><span class="rounded border border-ink/10 bg-white px-3 py-2 text-sm"><span class="text-amber-500">★</span> <b><?= e($featured['score']) ?></b> / 10</span></div><h3 class="mt-3 text-3xl"><?= e($featured['title']) ?></h3><div class="my-6 grid grid-cols-2 gap-5 border-y border-ink/10 py-5 text-xs leading-6"><div><b>What we like</b><?php foreach(explode("\n",$featured['pros']) as $p): ?><p class="mt-1 text-muted"><span class="text-teal">✓</span> <?= e($p) ?></p><?php endforeach ?></div><div><b>What could be better</b><?php foreach(explode("\n",$featured['cons']) as $p): ?><p class="mt-1 text-muted">− <?= e($p) ?></p><?php endforeach ?></div></div><div class="flex flex-wrap gap-3"><a class="btn" href="<?= e(reviewUrl($featured)) ?>">Read our verdict <?= icon('arrow','h-4 w-4') ?></a><a class="btn-light" href="/?page=compare&category=<?= e($featured['category_slug']) ?>">Compare options</a></div></div></div></section><?php endif ?>
<section class="wrap py-14"><div class="mb-8 flex items-end justify-between gap-4"><div><p class="eyebrow mb-3">Something for every day</p><h2 class="text-3xl sm:text-4xl">Explore your interests</h2></div><a href="/?page=categories" class="text-sm font-semibold text-teal">View all →</a></div><div class="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5"><?php foreach($cats as $c): ?><a href="/?page=reviews&category=<?= e($c['slug']) ?>" class="rounded-lg border border-ink/10 bg-white p-5 transition hover:border-teal hover:shadow-sm"><div class="mb-4 text-teal"><?= icon($c['icon'],'h-6 w-6') ?></div><h3 class="font-sans text-sm font-semibold"><?= e($c['name']) ?></h3><p class="mt-2 text-xs text-muted"><?= (int)$c['total'] ?> reviews <span class="float-right">↗</span></p></a><?php endforeach ?></div></section>
<section class="bg-ink text-white"><div class="wrap grid gap-8 py-11 md:grid-cols-4"><div><h2 class="text-3xl">Clarity comes first.</h2><p class="mt-3 text-sm leading-6 text-white/60">A considered approach to every review.</p><a class="mt-4 inline-block text-xs text-white underline underline-offset-4" href="/?page=about">How we review →</a></div><?php foreach(['01'=>['Research','Understand the features, the context and the choices.'],'02'=>['Compare','Look at the strengths and the trade-offs side by side.'],'03'=>['Explain','Turn the details into practical, readable advice.']] as $n=>[$t,$d]): ?><div class="border-white/15 md:border-l md:pl-7"><span class="text-xs tracking-widest text-teal-300"><?= $n ?></span><h3 class="mt-3 text-xl"><?= $t ?></h3><p class="mt-3 text-sm leading-6 text-white/60"><?= $d ?></p></div><?php endforeach ?></div></section>
<?php elseif($page==='reviews'||$page==='top10'):
 $q=trim((string)($_GET['q']??'')); $cat=(string)($_GET['category']??''); $sort=(string)($_GET['sort']??'latest');
 $where='WHERE r.status="published"'; $params=[];
 if($q!==''){$where.=' AND (r.title LIKE ? OR r.excerpt LIKE ?)';$params[]='%'.$q.'%';$params[]='%'.$q.'%';}
 if($cat!==''){$where.=' AND c.slug=?';$params[]=$cat;}
 $order=$page==='top10'||$sort==='score'?'r.score DESC,r.id DESC':'r.id DESC';
 $results=query($join.$where.' ORDER BY '.$order.($page==='top10'?' LIMIT 10':''),$params);
 $catName='';foreach($cats as $c)if($c['slug']===$cat)$catName=$c['name'];
?>
<section class="wrap py-12"><p class="eyebrow mb-4"><?= $page==='top10'?'The shortlist':'Find your next favourite' ?></p><h1 class="text-4xl sm:text-5xl"><?= e($catName?:($page==='top10'?'The top 10 edit':'Explore our reviews')) ?></h1><p class="mt-4 text-muted"><?= $page==='top10'?'Our highest-scoring published reviews. Demo scores are illustrative.':'Useful details and clear comparisons, all in one place.' ?></p><form class="my-8 grid gap-3 rounded-xl border border-ink/10 bg-white p-4 sm:grid-cols-4" action="/"><input type="hidden" name="page" value="<?= e($page) ?>"><div class="sm:col-span-2"><label class="label" for="q">Search reviews</label><input class="field" id="q" name="q" value="<?= e($q) ?>" placeholder="Search products, ideas and more"></div><div><label class="label" for="category">Category</label><select class="field" name="category" id="category"><option value="">All categories</option><?php foreach($cats as $c): ?><option value="<?= e($c['slug']) ?>" <?= $cat===$c['slug']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach ?></select></div><div><label class="label" for="sort">Sort by</label><div class="flex gap-2"><select class="field" id="sort" name="sort"><option value="latest">Latest</option><option value="score" <?= $sort==='score'?'selected':'' ?>>Highest score</option></select><button class="btn">Go</button></div></div></form><div class="mb-7 flex justify-between gap-4 text-sm"><span class="text-muted"><?= count($results) ?> reviews found</span><a class="font-semibold text-teal" href="/?page=compare&category=<?= e($cat) ?>">Compare reviews →</a></div><?php if(!$results): ?><div class="rounded-lg border border-ink/10 p-12 text-center"><h2 class="text-2xl">No reviews found</h2><p class="mt-3 text-muted">Try another keyword or explore a different category.</p><a class="btn mt-5" href="/?page=reviews">Clear filters</a></div><?php endif ?><div class="grid gap-x-8 gap-y-12 sm:grid-cols-2 lg:grid-cols-3"><?php foreach($results as $r) reviewCard($r); ?></div></section>
<?php elseif($page==='review'): $r=$review; ?>
<article class="wrap py-10"><nav class="mb-8 text-xs text-muted"><a href="/">Home</a> / <a href="/?page=reviews&category=<?= e($r['category_slug']) ?>"><?= e($r['category']) ?></a> / <?= $r['score']>0?'Review':'Article' ?></nav><div class="grid gap-10 lg:grid-cols-12"><div class="lg:col-span-8"><p class="eyebrow"><?= e($r['category']) ?> · <?= $r['demo']?'Sample review':($r['score']>0?'Editorial review':'Article') ?></p><h1 class="mt-4 text-4xl leading-tight sm:text-5xl"><?= e($r['title']) ?></h1><p class="mt-5 text-lg leading-8 text-muted"><?= e($r['excerpt']) ?></p><p class="my-5 text-xs text-muted">By <?= e($r['author']) ?> · Updated <?= e(date('F j, Y',strtotime($r['updated_at']))) ?></p><img class="aspect-[1.6] w-full rounded-xl object-cover" src="<?= e($r['image']) ?>" alt="<?= e($r['title']) ?>"><?php if($r['demo']): ?><p class="my-6 rounded-md border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">This is a sample review. Images, ratings and observations demonstrate the website and do not represent a verified product test.</p><?php endif ?><div class="prose-copy mt-8"><?= renderBody($r['body']) ?></div></div><aside class="lg:col-span-4"><?php if($r['score']>0): ?><div class="sticky top-6 rounded-xl border border-ink/10 bg-white p-6"><p class="eyebrow">Our verdict</p><div class="my-5"><span class="font-serif text-6xl"><?= number_format((float)$r['score'],1) ?></span><span class="text-muted"> / 10</span></div><p class="text-sm leading-7 text-muted"><?= e($r['verdict']) ?></p><div class="my-6 border-y border-ink/10 py-5"><h2 class="font-sans text-sm font-semibold">What we like</h2><?php foreach(explode("\n",$r['pros']) as $p): ?><p class="mt-3 text-sm text-muted"><span class="text-teal">✓</span> <?= e($p) ?></p><?php endforeach ?><h2 class="mt-6 font-sans text-sm font-semibold">What could be better</h2><?php foreach(explode("\n",$r['cons']) as $p): ?><p class="mt-3 text-sm text-muted">− <?= e($p) ?></p><?php endforeach ?></div><a class="btn w-full" href="/?page=compare&category=<?= e($r['category_slug']) ?>">Compare options →</a></div><?php else: ?><div class="sticky top-6 rounded-xl border border-ink/10 bg-white p-6"><p class="eyebrow">Disclosure</p><p class="mt-4 text-sm leading-7 text-muted">This article contains affiliate links. We may earn a commission if you make a purchase through them, at no extra cost to you.</p><a class="btn mt-6 w-full" href="/?page=reviews&category=<?= e($r['category_slug']) ?>">More in <?= e($r['category']) ?> →</a></div><?php endif ?></aside></div><section class="mt-14 border-t border-ink/10 pt-10"><h2 class="mb-8 text-3xl">Keep exploring</h2><div class="grid gap-8 md:grid-cols-3"><?php foreach(query($join.'WHERE r.status="published" AND r.id!=? ORDER BY (r.category_id=?) DESC,r.id DESC LIMIT 3',[$r['id'],$r['category_id']]) as $related)reviewCard($related); ?></div></section></article>
<?php elseif($page==='compare'):
 $cat=(string)($_GET['category']??'');$comp=query($join.'WHERE r.status="published" AND r.score>0'.($cat!==''?' AND c.slug=?':'').' ORDER BY r.score DESC LIMIT 3',$cat!==''?[$cat]:[]);
?><section class="wrap py-12"><p class="eyebrow">Side by side</p><h1 class="mt-4 text-4xl">A clearer comparison</h1><p class="mt-4 text-muted">Compare up to three highest-rated reviews in a category. Sample scores are illustrative.</p><form class="my-7 flex max-w-lg gap-3"><input type="hidden" name="page" value="compare"><label for="compare-cat" class="sr-only">Category</label><select class="field" id="compare-cat" name="category"><option value="">All categories</option><?php foreach($cats as $c): ?><option value="<?= e($c['slug']) ?>" <?= $cat===$c['slug']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach ?></select><button class="btn">Compare</button></form><?php if(!$comp): ?><p class="py-8 text-muted">No published reviews in this category yet.</p><?php else: ?><div class="grid gap-5 md:grid-cols-3"><?php foreach($comp as $r): ?><article class="overflow-hidden rounded-xl border border-ink/10 bg-white"><img src="<?= e($r['image']) ?>" alt="<?= e($r['title']) ?>" class="aspect-[1.6] w-full object-cover"><div class="p-6"><p class="eyebrow"><?= e($r['category']) ?><?= $r['demo']?' · Sample':'' ?></p><h2 class="mt-3 text-2xl"><?= e($r['title']) ?></h2><p class="my-5 text-3xl font-bold text-teal"><?= e($r['score']) ?><span class="text-sm font-normal text-muted"> / 10</span></p><h3 class="font-sans text-sm font-semibold">Pros</h3><p class="my-3 text-sm leading-7 text-muted"><?= nl2br(e($r['pros'])) ?></p><h3 class="font-sans text-sm font-semibold">Cons</h3><p class="my-3 text-sm leading-7 text-muted"><?= nl2br(e($r['cons'])) ?></p><a class="btn mt-5" href="<?= e(reviewUrl($r)) ?>">Read full review</a></div></article><?php endforeach ?></div><?php endif ?></section>
<?php elseif($page==='categories'): ?><section class="wrap py-12"><p class="eyebrow">Discover something useful</p><h1 class="mt-4 text-5xl">Everyday interests. Explored.</h1><p class="mt-5 text-muted">Find reviews and ideas in the categories that matter to you.</p><div class="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><?php foreach($cats as $c): ?><a class="rounded-xl border border-ink/10 bg-white p-7 hover:border-teal" href="/?page=reviews&category=<?= e($c['slug']) ?>"><div class="text-teal"><?= icon($c['icon'],'h-8 w-8') ?></div><h2 class="mt-5 text-2xl"><?= e($c['name']) ?></h2><p class="mt-3 text-sm text-muted"><?= (int)$c['total'] ?> reviews <span class="float-right text-teal">Explore →</span></p></a><?php endforeach ?></div></section>
<?php elseif($page==='about'||$page==='privacy'): ?><section class="wrap max-w-4xl py-14"><p class="eyebrow"><?= $page==='about'?'Behind the reviews':'Your information' ?></p><h1 class="mb-8 mt-4 text-5xl"><?= $page==='about'?'Clarity comes first.':'Privacy' ?></h1><div class="prose-copy"><?php if($page==='about'): ?><p>Best Top 10 Things is a place to explore product and service reviews across the things that make up everyday life.</p><h2 class="mb-4 text-2xl">Research, compare, explain</h2><p>Our editorial framework focuses on usefulness, ease of use, features and value. Each review has space for a score, strengths, limitations and a clear verdict, so readers can see the reasoning behind a recommendation.</p><h2 class="mb-4 text-2xl">A note about this demo</h2><p>The initial articles are clearly labelled sample reviews. Their scores and observations are illustrative. They are not claims of hands-on testing. Editors should replace these with original research and disclose sources, testing methods and commercial relationships before publishing real recommendations.</p><?php else: ?><p>This website stores essential session cookies for secure CMS login and form protection. Public browsing does not require an account.</p><p>CMS account information and editorial content are stored in the site's database. Failed login attempts are temporarily recorded to limit repeated attempts. The site does not include analytics or advertising trackers by default.</p><p>Images configured by editors may load from third-party HTTPS hosts. Those hosts receive the network information needed to serve an image. Website server logs may also record requests.</p><p>This starter privacy text should be updated by the site operator to describe the actual hosting, retention practices, contact details and any additional services used at launch.</p><?php endif ?></div></section>
<?php else: ?><section class="wrap py-24 text-center"><p class="eyebrow">404</p><h1 class="mt-5 text-4xl">This page took a different path.</h1><a class="btn mt-8" href="/">Back to home</a></section><?php endif ?>
</main>
<?php footerView(); ?>
